//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetsGame.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PetsGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your pet wants to go for a walk.
        /// </summary>
        internal static string commentEight {
            get {
                return ResourceManager.GetString("commentEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your pet tore your jacket..
        /// </summary>
        internal static string commentEleven {
            get {
                return ResourceManager.GetString("commentEleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You can always erase your statistics. (but what for?).
        /// </summary>
        internal static string commentFive {
            get {
                return ResourceManager.GetString("commentFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Consider taking a break..
        /// </summary>
        internal static string commentFour {
            get {
                return ResourceManager.GetString("commentFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your pet loves you..
        /// </summary>
        internal static string commentNine {
            get {
                return ResourceManager.GetString("commentNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your pet dreamt of you tonight..
        /// </summary>
        internal static string commentOne {
            get {
                return ResourceManager.GetString("commentOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your pet has woken up..
        /// </summary>
        internal static string commentSeven {
            get {
                return ResourceManager.GetString("commentSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your pet have met another pet for the first time..
        /// </summary>
        internal static string commentSix {
            get {
                return ResourceManager.GetString("commentSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A big bone is very useful if you&apos;re tired of feeding your pet..
        /// </summary>
        internal static string commentTen {
            get {
                return ResourceManager.GetString("commentTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The name is very important (e.g. a parrot called Rex is aggressive)..
        /// </summary>
        internal static string commentThirteen {
            get {
                return ResourceManager.GetString("commentThirteen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a There&apos;s a secret pet..
        /// </summary>
        internal static string commentThree {
            get {
                return ResourceManager.GetString("commentThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Never kick your pet..
        /// </summary>
        internal static string commentTwelve {
            get {
                return ResourceManager.GetString("commentTwelve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Play more and win to unlock other pets..
        /// </summary>
        internal static string commentTwo {
            get {
                return ResourceManager.GetString("commentTwo", resourceCulture);
            }
        }
    }
}
